version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: nerus-tvheadend_tvheadend_1
      APP_PORT: 9981

  tvheadend:
    image: lscr.io/linuxserver/tvheadend:latest
    container_name: tvheadend
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - ${APP_DATA_DIR}/config:/config
      - ${APP_DATA_DIR}/recordings:/recordings
    restart: unless-stopped
